server.description=Production
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

mail.host=${MAIL_HOST}
mail.port=${MAIL_PORT}
mail.username=${MAIL_USERNAME}
mail.password=${MAIL_PASSWORD}
mail.debug=${MAIL_DEBUG}
mail.auth=${MAIL_AUTH}
mail.starttls-enable=${MAIL_STARTTLS_ENABLE}