spring.application.name=backend
server.port=8081
spring.profiles.active=prod
server.description=Main

api.base.path=api/v1
application.initial-name=initialName
application.contact.info=pthu1@kmd.edu.mm
application.version=1.0
application.host.url=http://localhost
application.frontend-urls=http://localhost:5173, http://localhost:5174, https://ewsd-frontend-app.vercel.app, http://192.168.1.118:5173, http://150.95.83.208:9999

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Actuator
management.endpoints.web.base-path=/manage
management.endpoint.health.group.custom.include=diskSpace,ping
management.endpoint.health.group.custom.show-components=when_authorized
management.endpoint.health.group.custom.show-details=when_authorized
management.endpoint.health.group.custom.status.http-mapping.up=207
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=loggers

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

org.slf4j.simpleLogger.defaultLogLevel=INFO

org.slf4j.simpleLogger.log.org.teamSmurfs.backend=DEBUG
org.slf4j.simpleLogger.log.org.springframework=WARN

org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss
org.slf4j.simpleLogger.showThreadName=true

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG